ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from home.views import home_view
from signup.views import signup_view
from products.views import ProductListView
from carts.views import CartView
from django.contrib.auth import views as auth_view
urlpatterns = [
    path('admin/', admin.site.urls),
    # product
    path('products/',include('products.urls')),
    path('', home_view, name='home_view'),

    # category
    path('categories/',include('products.urls_categories')),
    # Cart
    path('cart/', CartView.as_view(), name='cart'),
    # authentications 
    path('signup/',signup_view, name='signup'),
    path('accounts/',include("django.contrib.auth.urls")),
    path('change_password', auth_view.PasswordChangeView.as_view(
        template_name = 'registration/password_change.html',
        success_url = '/'
    ), name='change_password' ),
    path('reset_password', auth_view.PasswordResetView.as_view(
    template_name = 'registration/password_reset.html',
    success_url = 'accounts/login'),
    name='reset_password' ),
] 
    # media_url and static_url
urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/urls.py
from django.urls import path
from .views import ProductDetailView,  ProductListView, VariationListView


app_name='products'
urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('<int:pk>/', ProductDetailView.as_view(), name='product_details'),
    path('<int:pk>/inventory/', VariationListView.as_view(), name='product_inventory'),


]

templates/base.html
{% load static %}  
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">  
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>E4C</title>
        <link href=" {% static 'css/bootstrap.min.css' %}" rel="stylesheet" >
        <link href=" {% static 'css/font-awesome.min.css' %}" rel="stylesheet" >
        <link href=" {% static 'css/base.css' %}" rel="stylesheet" >
        <link rel="icon" href="{% static 'favicon.ico' %}">

    </head>
    <style>
      {% block style%}
      {%endblock%}
    </style>
    <body>
      {% include 'navbar.html'%}
      <div class="container">
      {% if messages %}
      <div class="alert alert-success alert-dismissible text-center" role="alert">
        {% for message in messages %}
        <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

        {% endfor %}
      </div>

      {% endif %}
    </div>
      {%block title%}
      {%endblock%}
      
      {%block content%}
      {%endblock%}
      
      <!-- {% include 'footer.html'%} -->
      <style>
        .endFooter{
            background-color: black;
            color:rgb(196, 192, 192);
            /* position:sticky;
            bottom: 0;
            left: 0;
            right: 0; */
        
        
        }
        .endFooter p{
            font-weight: normal;
            letter-spacing: 2px;
            color: #666666;
            margin: 0;
        
        }
        .endFooter .row{
            padding: 16px;
        }
        
        .endFooter ul{
            margin: 0;
        }
        .endFooter .sam{
            text-align: right;
        }
        .endFooter ul li{
            display: inline;
            font-size: 18px;
            margin-left: 30px;
        }
        .endFooter ul li a{
            text-decoration: none;
            color: #666666;
        
        }
        </style>
        <footer class="endFooter">
            <div class="container">
            <div class="row ">
            <div class="col-sm-6 text-center text-sm-left text-uppercase">
                <p>&copy;Copyright 2021 E4C</p>
            </div>
            <div class="col-sm-6 text-center text-sm-right">
                <ul class="social-links list-unstyled">
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-youtube"></i></a></li>
                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                <li><a href="#"><i class="fa fa-instagram"></i></a></li>
        
                </ul>
                
            </div>
            </div>
        </div>
        </footer>
      <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
      <script src="{% static 'js/popper.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <script>
        $(document).ready(function(){
          {% block jquery %}

          {% endblock %}

        });
      </script>  
    </body>
</html>

templates/footer.html
{% load static %}
<style>
.endFooter{
    background-color: black;
    color:rgb(196, 192, 192);


}
.endFooter p{
    font-weight: normal;
    letter-spacing: 2px;
    color: #666666;
    margin: 0;

}
.endFooter .row{
    padding: 16px;
}

.endFooter ul{
    margin: 0;
}
.endFooter .sam{
    text-align: right;
}
.endFooter ul li{
    display: inline;
    font-size: 18px;
    margin-left: 30px;
}
.endFooter ul li a{
    text-decoration: none;
    color: #666666;

}
</style>
<footer class="endFooter">
    <div class="container">
    <div class="row ">
    <div class="col-sm-6 text-center text-sm-left text-uppercase">
        <p>&copy;Copyright 2021 E4C</p>
    </div>
    <div class="col-sm-6 text-center text-sm-right">
        <ul class="social-links list-unstyled">
        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
        <li><a href="#"><i class="fa fa-youtube"></i></a></li>
        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
        <li><a href="#"><i class="fa fa-instagram"></i></a></li>

        </ul>
        
    </div>
    </div>
</div>
</footer>

templates/navbar.html
{% load static %}
<style>
.navbar{
    margin-bottom: 20px;
    background-color: orange;
    
}
.navbar-light .navbar-nav .nav-link{
    color: #fff;
    font-weight: bold;
    text-transform: uppercase;

}


.navbar-light .navbar-nav .nav-link span{
    color: #000;


}
.navbar-brand img{
    border: 5px solid white;
    border-radius: 50%;
}
.shopping-icon{
    font-size: 28px;

}
.shopping-icon-span{
    color:orange !important;
    background-color: #000;
    border-radius: 50%;
    vertical-align:text-top;
    font-size: 10px;
    margin-left: -10px;

}
 .log-item{
    font-weight: 500;
    color: orange;
    text-align: center;
    text-transform: uppercase;
    border: 1px solid #fff;
}
/*
.log-item-in{
    border-top: none;
    border-bottom: 2px solid rgb(207, 207, 207);

} */
.settings{
    color: orange !important;
    text-transform: uppercase;
    font-weight: 500;
    font-size: 14px;

}

</style>
<!-- start navbar -->
<nav class="navbar navbar-expand-lg navbar-light" > 
    <div class="container">
        <a class="navbar-brand"  href="/" >
            <img src="{% static 'favicon.ico' %}" alt=""  class="d-inline-block align-top">
        </a>
        <form class="d-flex" role="search" method="GET" action='{% url "products:product_list" %}'>
            <input class="form-control" type="search" placeholder="Search" aria-label="Search" name="q">
            <button type="submit" style="margin-left: -10px; color: white; background: black; border: none;  border-radius: 10%;"><i class="fa fa-search"></i></button>
        </form>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <!-- home -->
            <li class="nav-item">
                <a class="nav-link " aria-current="page" href="/">Home</a>
            </li>
            <!-- settings + logout -->
            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Hi, {{user}}
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <li><a class="dropdown-item settings" href="{% url 'change_password'%}">change password</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li>
                    <a class="dropdown-item log-item btn-more" href="{% url 'logout' %}">logout</a>
                    </li>
                </ul>
              </li>

            {% else %}
            <!-- login -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    log<span class="block">in</span>
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">  
                  <li>
                    <a class="dropdown-item log-item log-item-in btn-more" href="{% url 'login' %}">login</a>
                  </li>
                  <li><hr class="dropdown-divider"></li>

                  <li><a class="dropdown-item settings" href="{% url 'signup'%}">Create New Account</a></li>

                </ul>
              </li>

            {% endif %}
                <!-- shopping cart -->

                <li class="nav-item">
                <a class="nav-link " href="#"><i class="fa fa-shopping-cart shopping-icon"><span class="badge shopping-icon-span">10</span></i></a>
                </li>
        </ul>
        </div>
    </div>
</nav> 
<!-- end navbar -->